
max_fpr: 0.1
decision_threshold: 0.9

feature:
  n_mels: 128
  n_frames: 5
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

fit:
  lr: 0.001
  epochs: 100
  batch_size: 512
  shuffle: True
  validation_split: 0.1
  verbose: 1

ssh:
  remote_ip: server_ip
  username: username
  private_key_path: path/to/private_key
  conda_environment: conda_environment_name
